import type { Metadata } from "next";
import localFont from "next/font/local";
import { Karla } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";

const karla = Karla({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${karla.className} antialiased relative`}>
        <Navbar />
        <div>{children}</div>
      </body>
    </html>
  );
}
